### PR TITLE
Fix compile errors that has unused arguments or variables

### LINKED ISSUE #668: [Bug] The current HEAD of main no longer builds on Rocky Linux 8 & 9.
### Cloudberry Database version

Cloudberrydb main branch (fdc5abc0ca)

### What happened

Compilation error:

```
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-but-set-variable -Werror=implicit-fallthrough=3 -Wno-format-truncation -Wno-stringop-truncation -O3 -fPIC  -DUSE_INTERNAL_FTS=1  -Werror=uninitialized -Werror=implicit-function-declaration -Werror -I../../../../src/interfaces/libpq -I../../../../src/include   -D_GNU_SOURCE -I/usr/include/libxml2   -c -o appendonlyam.o appendonlyam.c
appendonlyam.c: In function ‘appendonly_insert’:
appendonlyam.c:3052:9: error: unused variable ‘firstSequence’ [-Werror=unused-variable]
   int64 firstSequence = GetFastSequences(aoInsertDesc->segrelid,
         ^~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

### What you think should happen instead

This is a relatively new issue. I am able to build at `781c43b63b`.

### How to reproduce

Following the documentation: For RHEL 8 and Rocky Linux 8 (https://cloudberrydb.org/docs/cbdb-linux-compile).

```
./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/usr/local/cloudberrydb
make
```

### Operating System

Rocky Linux 8 & 9

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

### PR DESCRIPTION
**Pull request by gfphoenix78**
fix #668 

### Contributor's Checklist

Here are some reminders and checklists before/when submitting your pull request, please check them:

- [ ] Make sure your Pull Request has a clear title and commit message. You can take [git-commit](https://github.com/cloudberrydb/cloudberrydb/blob/main/.gitmessage) template as a reference.
- [ ] Sign the Contributor License Agreement as prompted for your first-time contribution(*One-time setup*).
- [ ] Learn the [coding contribution guide](https://cloudberrydb.org/contribute/code), including our code conventions, workflow and more.
- [ ] List your communication in the [GitHub Issues](https://github.com/cloudberrydb/cloudberrydb/issues) or [Discussions](https://github.com/orgs/cloudberrydb/discussions) (if has or needed).
- [ ] Document changes.
- [ ] Add tests for the change
- [ ] Pass `make installcheck`
- [ ] Pass `make -C src/test installcheck-cbdb-parallel`
- [ ] Feel free to request `cloudberrydb/dev` team for review and approval when your PR is ready🥳

### CODE REVIEW

File: src/backend/access/appendonly/appendonlyam.c [hunk 1]
```diff
@@ -3054,6 +3054,7 @@ appendonly_insert(AppendOnlyInsertDesc aoInsertDesc,
 											   aoInsertDesc->lastSequence + 1,
 											   NUM_FAST_SEQUENCES);
 
+		(void)firstSequence;
```
Comment (avamingli) [inline src/backend/access/appendonly/appendonlyam.c:3057]: What's the magic here :)

**Comment by edespino** [comment]
This PR compiles on Rocky Linux 8, 9 and Ubuntu 22 and `make create-demo-cluster` work. I am now running `installcheck` on the same platforms.

```
    psql -P pager=off template1 -c 'SELECT version()'
                                                                                         version                                                                                         
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 14.4 (Cloudberry Database 1.0.0+b7744db7b7 build 1) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-22), 64-bit compiled on Oct 16 2024 05:52:00

```

**Review by edespino — APPROVED** [review]
The PR (7fbcbacc30), successfully was built with my standard configure release build and debug build options.

Here are the version strings for the respective platforms I tested on:

**Rocky Linux: 8.10 (Green Obsidian)**
```
PostgreSQL 14.4 (Cloudberry Database 1.0.0+7fbcbacc30 build dev) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-22), 64-bit compiled on Oct 16 2024 07:07:26
```

**Rocky Linux: 9.4 (Blue Onyx)**

```
PostgreSQL 14.4 (Cloudberry Database 1.0.0+7fbcbacc30 build dev) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3), 64-bit compiled on Oct 16 2024 07:07:35 (with assert checking)
```

**Ubuntu: 22.04.4 LTS (Jammy Jellyfish)**
```
PostgreSQL 14.4 (Cloudberry Database 1.0.0+7fbcbacc30 build dev) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit compiled on Oct 16 2024 07:09:13
```

Standard `make create-demo-cluster` and `make installcheck` (with and without orca) performed satisfactorily.

**Review by avamingli — APPROVED** [review]
